HospitalManagementSystemCore/Pages/ADMIN/AdminAdd.cshtml.cs
using HospitalManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HospitalManagementSystem.Pages.ADMIN
{
    public class AdminAddModel : PageModel
    {
        private readonly ILogger<AdminAddModel> _logger;
        private readonly HosDB HDB;
        public string sid { get; set; }

        public string mname { get; set; }
        public AdminAddModel(ILogger<AdminAddModel> logger, HosDB HosDB)
        {
            _logger = logger;
            this.HDB = HosDB;
        }
        public void OnGet()
        {
            sid = HttpContext.Session.GetString("sid");
            mname = HDB.getStaffFnameByID(sid);
        }

            public IActionResult OnPost()
        {
            string selected = HttpContext.Request.Form["selectedItem"];
            if (string.IsNullOrEmpty(selected))
            {
                return Page();
            }
            else
            {
                List<object> list = new List<object>();
                if (selected == "doctor")
                {
                    string fName = HttpContext.Request.Form["first-name"];
                    string lName = HttpContext.Request.Form["last-name"];
                    string staffId = HttpContext.Request.Form["staff-id"];
                    string nationalId = HttpContext.Request.Form["national-id"];
                    int deptNumber = int.Parse(HttpContext.Request.Form["dept-number"]);
                    int age = int.Parse(HttpContext.Request.Form["age"]);
                    string gender = HttpContext.Request.Form["gender"];
                    char g;
                    if (gender == "male")
                    {
                        g = 'M';
                    }
                    else
                    {
                        g = 'F';
                    }
                    string street = HttpContext.Request.Form["street"];
                    string city = HttpContext.Request.Form["city"];
                    string governorate = HttpContext.Request.Form["governorate"];
                    string phone = HttpContext.Request.Form["phone"];
                    string password = HttpContext.Request.Form["password"];
                    string email = HttpContext.Request.Form["staff-email"];
                    list.Add(fName);
                    list.Add(lName);
                    list.Add(staffId);
                    list.Add(nationalId);
                    list.Add(deptNumber);
                    list.Add(age);
                    list.Add(g);
                    list.Add(street);
                    list.Add(city);
                    list.Add(governorate);
                    list.Add(phone);
                    list.Add(password);
                    list.Add(email);
                    HDB.addMedicalStaff(selected, list);
                }
                else if(selected == "nurse")
                {
                    string fName = HttpContext.Request.Form["first-name"];
                    string lName = HttpContext.Request.Form["last-name"];
                    string staffId = HttpContext.Request.Form["staff-id"];
                    string nationalId = HttpContext.Request.Form["national-id"];
                    int deptNumber = int.Parse(HttpContext.Request.Form["dept-number"]);
                    int age = int.Parse(HttpContext.Request.Form["age"]);
                    string gender = HttpContext.Request.Form["gender"];
                    char g;
                    if (gender == "male")
                    {
                        g = 'M';
                    }
                    else
                    {
                        g = 'F';
                    }
                    string street = HttpContext.Request.Form["street"];
                    string city = HttpContext.Request.Form["city"];
                    string governorate = HttpContext.Request.Form["governorate"];
                    string phone = HttpContext.Request.Form["phone"];
                    string password = HttpContext.Request.Form["password"];
                    string email = HttpContext.Request.Form["staff-email"];
                    list.Add(fName);
                    list.Add(lName);
                    list.Add(staffId);
                    list.Add(nationalId);
                    list.Add(deptNumber);
                    list.Add(age);
                    list.Add(g);
                    list.Add(phone);
                    list.Add(street);
                    list.Add(city);
                    list.Add(governorate);
                    list.Add(password);
                    list.Add(email);
                    HDB.addMedicalStaff(selected, list);
                }
                else if(selected == "pharmacist")
                {
                    string fName = HttpContext.Request.Form["first-name"];
                    string lName = HttpContext.Request.Form["last-name"];
                    string staffId = HttpContext.Request.Form["staff-id"];
                    string nationalId = HttpContext.Request.Form["national-id"];
                    int age = int.Parse(HttpContext.Request.Form["age"]);
                    string gender = HttpContext.Request.Form["gender"];
                    char g;
                    if (gender == "male")
                    {
                        g = 'M';
                    }
                    else
                    {
                        g = 'F';
                    }
                    string street = HttpContext.Request.Form["street"];
                    string city = HttpContext.Request.Form["city"];
                    string governorate = HttpContext.Request.Form["governorate"];
                    string phone = HttpContext.Request.Form["phone"];
                    string password = HttpContext.Request.Form["password"];
                    string email = HttpContext.Request.Form["staff-email"];
                    list.Add(fName);
                    list.Add(lName);
                    list.Add(staffId);
                    list.Add(nationalId);
                    list.Add(age);
                    list.Add(g);
                    list.Add(phone);
                    list.Add(street);
                    list.Add(city);
                    list.Add(governorate);
                    list.Add(password);
                    list.Add(email);
                    HDB.addMedicalStaff(selected, list);
                }
                else if (selected == "labtechnician")
                {
                    string fName = HttpContext.Request.Form["first-name"];
                    string lName = HttpContext.Request.Form["last-name"];
                    string staffId = HttpContext.Request.Form["staff-id"];
                    string nationalId = HttpContext.Request.Form["national-id"];
                    int age = int.Parse(HttpContext.Request.Form["age"]);
                    string gender = HttpContext.Request.Form["gender"];
                    char g;
                    if (gender == "male")
                    {
                        g = 'M';
                    }
                    else
                    {
                        g = 'F';
                    }
                    string street = HttpContext.Request.Form["street"];
                    string city = HttpContext.Request.Form["city"];
                    string governorate = HttpContext.Request.Form["governorate"];
                    string phone = HttpContext.Request.Form["phone"];
                    string password = HttpContext.Request.Form["password"];
                    string email = HttpContext.Request.Form["staff-email"];
                    list.Add(fName);
                    list.Add(lName);
                    list.Add(staffId);
                    list.Add(nationalId);
                    list.Add(age);
                    list.Add(g);
                    list.Add(phone);
                    list.Add(street);
                    list.Add(city);
                    list.Add(governorate);
                    list.Add(password);
                    list.Add(email);
                    HDB.addMedicalStaff(selected, list);
                }
                else if(selected == "NURSE_SERVE_AT")
                {
                    string room_id = HttpContext.Request.Form["roomid"];
                    string nurse_id = HttpContext.Request.Form["nurseid"];
                    string day = HttpContext.Request.Form["day"];
                    string start_time = HttpContext.Request.Form["start-time"];
                    string end_time = HttpContext.Request.Form["end-time"];
                    list.Add (room_id);
                    list.Add (nurse_id);
                    list.Add (day);
                    list.Add (start_time);
                    list.Add (end_time);
                    HDB.addMedicalStaff(selected, list);

                }
                else if (selected == "DOCTOR_WORK_AT")
                {
                    string room_id = HttpContext.Request.Form["roomid"];
                    string doctor_id = HttpContext.Request.Form["doctorid"];
                    string day = HttpContext.Request.Form["day"];
                    string start_time = HttpContext.Request.Form["start-time"];
                    string end_time = HttpContext.Request.Form["end-time"];
                    list.Add(room_id);
                    list.Add(doctor_id);
                    list.Add(day);
                    list.Add(start_time);
                    list.Add(end_time);
                    HDB.addMedicalStaff(selected, list);

                }
                else
                {
                    string Name = HttpContext.Request.Form["name"];
                    int deptNumber = int.Parse(HttpContext.Request.Form["dept-number"]);
                    string specialty = HttpContext.Request.Form["specialty"];
                    list.Add (Name);

HospitalManagementSystemCore/Pages/ADMIN/AdminAnnouncements.cshtml.cs
using HospitalManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using System.Data;

namespace HospitalManagementSystem.Pages.ADMIN
{
    public class AdminAnnouncmentscshtmlModel : PageModel
    {
        private readonly ILogger<AdminAnnouncmentscshtmlModel> _logger;
        private readonly HosDB db;
        public string sid { get; set; }

        public DataTable annc { get; set; }


        public string mname { get; set; }
        public AdminAnnouncmentscshtmlModel(ILogger<AdminAnnouncmentscshtmlModel> logger, HosDB HosDB)
        {
            _logger = logger;
            this.db = HosDB;
        }
        public void OnGet()
        {
            sid = HttpContext.Session.GetString("sid");
            mname = db.getStaffFnameByID(sid);
            annc = db.getAnnc();
        }
    }
}

HospitalManagementSystemCore/Pages/ADMIN/AdminDash.cshtml.cs
using HospitalManagementSystem.Models;
using HospitalManagementSystem.Pages.Manager_Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using System.Data;

namespace HospitalManagementSystem.Pages.ADMIN
{
    public class AdminDashModel : PageModel
    {

        private readonly ILogger<AdminDashModel> _logger;
        private readonly HosDB db;
        public string sid { get; set; }

        public string mname { get; set; }
        public DataTable annc { get; set; }
        public AdminDashModel(ILogger<AdminDashModel> logger, HosDB HosDB)
        {
            _logger = logger;
            this.db = HosDB;
        }
        public void OnGet()
        {

            sid = HttpContext.Session.GetString("sid");
            mname = db.getStaffFnameByID(sid);
            annc = db.getAnnc();
        }
    }
}

HospitalManagementSystemCore/Pages/ADMIN/AdminViewTables.cshtml.cs
using HospitalManagementSystem.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Data;
using System.Xml.Linq;
using Newtonsoft.Json;


namespace HospitalManagementSystem.Pages.Admin
{
    public class AdminViewTablesModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly HosDB db;
        public DataTable Datatable { get; set; }
        [BindProperty(SupportsGet = true)]
        public String profession { get; set; }
        public Dictionary<String,Tuple<List<String>,int>> professions { get; set; }

        public string sid { get; set; }
        public string mname { get; set; }

        public AdminViewTablesModel(ILogger<IndexModel> logger, HosDB db)
        {
            _logger = logger;
            this.db = db;
                   
            
            professions = new Dictionary<String, Tuple<List<String>, int>>()
            {
                {
                    "Doctor",
                    new Tuple<List<String>, int>(
                    new List<String>(){"First Name","Last Name","Staff ID","National ID","Department Number","Age","Gender","Street","City","Governorate","Phone Number", "Password", "Staff_Email"},
                    10
                )
            },
                {
                    "Nurse",
                    new Tuple<List<String>, int>(
                    new List<String>(){"First Name","Last Name","Staff ID","National ID","Department Number","Age","Gender","Street","City","Governorate","Phone Number", "Password", "Staff_Email"},
                    10
                )
            },
                {
                    "Pharmacist",
                    new Tuple<List<String>, int>(
                    new List<String>(){"First Name","Last Name","Staff ID","National ID","Age","Gender", "Phone Number", "Street","City","Governorate", "Password", "Staff_Email"},
                    10
                )
            },
                {
                    "LabTechnician",
                    new Tuple<List<String>, int>(
                    new List<String>(){"First Name","Last Name","Staff ID","National ID","Age","Gender","Street","City","Governorate","Phone Number", "Password", "Staff_Email"},
                    10
                )
            },
                {
                    "Department",
                    new Tuple<List<String>, int>(
                    new List<String>(){"Name", "Specialty", "Department Number"},
                    3
                )
            },
                {
                    "Patient",
                    new Tuple<List<String>, int>(
                    new List<String>(){"First Name","Last Name","Patient ID","National ID","Age","Gender","Street","City","Governorate","Phone Number"},
                    9
                )
            },
                {
                    "NURSE_SERVE_AT",
                    new Tuple<List<String>, int>(
                    new List<String>(){"Room ID","Nurse ID","Working Day","Start Hour","End Hour"},
                    5
                )
            },
                {
                    "DOCTOR_WORK_AT",
                    new Tuple<List<String>, int>(
                    new List<String>(){"Room ID","Doctor ID","Working Day","Start Hour","End Hour"},
                    5
                )
            },
        };
        }
        public void OnGet()
        {
            sid = HttpContext.Session.GetString("sid");
            mname = db.getStaffFnameByID(sid);
            Datatable = db.GetTableAdmin(profession);
            
        }
        public IActionResult OnPost()
        {
            string ID = HttpContext.Request.Form["selectedItem"];
            string profession = HttpContext.Request.Form["profession"];
            db.RemoveUserAdmin(JsonConvert.DeserializeObject<List<string>>(ID), profession);

            return RedirectToPage("/Admin/AdminViewTables",new { profession = this.profession });
        }
        public IActionResult OnPostEdit() {

            string ID = HttpContext.Request.Form["selectedItem"];
            string profession = HttpContext.Request.Form["profession"];
            var routeValues = new { profession = profession, ID = ID };

            return RedirectToPage("/Admin/AdminEdit", routeValues);
        }
    }
}

HospitalManagementSystemCore/Pages/ADMIN/AdminAnnouncements.cshtml
@page
@model HospitalManagementSystem.Pages.ADMIN.AdminAnnouncmentscshtmlModel
@{
    Layout = "_LayoutAdmin";
}

        <div class="container-fluid">
    <div class="d-sm-flex ml-5 mb-2 mt-3">
        <h1 class="h3 mb-0 " style="font-family: 'Poppins';color: #4E4E4E;">Welcome, </h1>
        <h1 class="h3 mb-0 " style="font-family: 'Poppins';color:#1390D6;">@Model.mname</h1>
    </div>
            <section>
                <div class="row">

                    <div class="col-lg-12">
                <div class="card" style="border-radius: 1rem 1rem 1rem 1rem;">
                            <div class="card-title">
                        <h2 class="h3 m-4 grey-text" style="font-family: 'Poppins';">Announcements</h2>

                            </div>
                            <div class="card-body">
                        @for (int i = 0; i < Model.annc.Rows.Count; i++)
                        {
                            <div class="card">
                                <div class="card-title">
                                    @Model.annc.Rows[i][0]
                                </div>
                                <div class="card-body">
                                    <div class="ct-bar-chart m-t-30">
                                        <p>@Model.annc.Rows[i][2]</p>
                                    </div>
                                </div>
                                <div class="float-xl-end">@Model.annc.Rows[i][1]</div>
                            </div>
                        }
                            </div>
                        </div>
                    </div>
                </div>

            </section>
        </div>

HospitalManagementSystemCore/Pages/ADMIN/AdminDash.cshtml
@page
@model HospitalManagementSystem.Pages.ADMIN.AdminDashModel
@{
    Layout = "_LayoutAdmin";
}

<div class="container-fluid">
    <div class="d-sm-flex ml-5 mb-2 mt-3">
        <h1 class="h3 mb-0 " style="font-family: 'Poppins';color: #4E4E4E;">Welcome, </h1>
        <h1 class="h3 mb-0 " style="font-family: 'Poppins';color:#1390D6;">@Model.mname</h1>
    </div>
    <section>
        <div class="row">
            <div class="col-lg-12">
                <div class="card" style="border-radius: 1rem 1rem 1rem 1rem;">
                    <h2 class="h3 m-4 grey-text" style="font-family: 'Poppins';">Current Users</h2>
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Department Number</th>
                                    <th>Speciality</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Cardiology</td>
                                    <td>1</td>
                                    <td>Heart</td>
                                    <td><button onclick="deleteRow(this)">Delete</button></td>
                                </tr>
                                <tr>
                                    <td>Dentistry</td>
                                    <td>2</td>
                                    <td>Teeth</td>
                                    <td><button onclick="deleteRow(this)">Delete</button></td>
                                </tr>
                                <tr>
                                    <td>Neurology</td>
                                    <td>3</td>
                                    <td>Brain</td>
                                    <td><button onclick="deleteRow(this)">Delete</button></td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="float-xl-end"><a href="/ADMIN/AdminView">See more</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card" style="border-radius: 1rem 1rem 1rem 1rem;">
                    <div class="card-title">
                        <h2 class="h3 m-4 grey-text" style="font-family: 'Poppins';">Announcements</h2>

                    </div>
                    <div class="card-body">
                        <div class="card-body">
                            <div class="card">
                                @for (int i = 0; i < Math.Min(Model.annc.Rows.Count, 2); i++)
                                {
                                    <div class="card">
                                        <div class="card-title">
                                            @Model.annc.Rows[i][0]
                                        </div>
                                        <div class="card-body">
                                            <div class="ct-bar-chart m-t-30">
                                                <p>@Model.annc.Rows[i][2]</p>
                                            </div>
                                        </div>
                                        <div class="float-xl-end">@Model.annc.Rows[i][1]</div>
                                    </div>
                                }


                                <div class="float-xl-end"><a href="/Admin/AdminAnnouncements">See more</a></div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
        </section>
</div>

HospitalManagementSystemCore/Pages/ADMIN/AdminEdit.cshtml
@page
@model HospitalManagementSystem.Pages.Admin.AdminEditModel
@{
    Layout = "_LayoutAdmin";
}

<div class="container-fluid">
    <div class="d-sm-flex ml-5 mb-2 mt-3">
        <h1 class="h3 mb-0 " style="font-family: 'Poppins';color: #4E4E4E;">Welcome, </h1>
        <h1 class="h3 mb-0 " style="font-family: 'Poppins';color:#1390D6;">@Model.mname</h1>
    </div>
    <section>
        <div class="row">
            <div class="col-lg-12">
                <div class="card" style="border-radius: 1rem 1rem 1rem 1rem;">
                    <h2 class="h3 m-4 grey-text" style="font-family: 'Poppins';">Edit @Model.profession with ID = @Model.ID </h2>
                    <div class="card-body">
                        <form method="post">
                            @for (int i = 0; i < Model.professions[Model.profession].Item2.Count; i++)
                            {
                                <input type="text" name="@Model.professions[Model.profession].Item2[i]" id="@Model.professions[Model.profession].Item2[i]" value="@Model.Datatable.Rows[0][i]" placeholder="@Model.professions[Model.profession].Item1[i]" required>
                            }
                            <input class="btn btn-primary" type="submit" value="Submit">
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </section>
</div>

HospitalManagementSystemCore/Pages/ADMIN/AdminViewTables.cshtml
@page
@using Newtonsoft.Json;
@model HospitalManagementSystem.Pages.Admin.AdminViewTablesModel
@{
    Layout = "_LayoutAdmin";
}

<div class="container-fluid">
    <div class="d-sm-flex ml-5 mb-2 mt-3">
        <h1 class="h3 mb-0 " style="font-family: 'Poppins';color: #4E4E4E;">Welcome, </h1>
        <h1 class="h3 mb-0 " style="font-family: 'Poppins';color:#1390D6;">@Model.mname</h1>
    </div>
    <section>
        <div class="row">
            <div class="col-lg-12">
                <div class="card" style="border-radius: 1rem 1rem 1rem 1rem;">
                    <h2 class="h3 m-4 grey-text" style="font-family: 'Poppins';">@(Model.profession == "NURSE_SERVE_AT" ? "Nurse Serve At" : Model.profession)</h2>
                    <div class="card-body">
                        <input type="text" id="search-input" placeholder="Search by Staff ID">
                        <div class="overflow-auto h-100">
                        <table class="table table-hover" id="doctors">
                            <thead>
                                <tr>
                                    @for(int i = 0; i < Model.professions[Model.profession].Item2;i++)
                                    {
                                    <th>@Model.professions[Model.profession].Item1[i]</th>
                                    }
                                        <th>Edit</th>
                                <th>Delete</th>
                                    </tr>
                                </thead>
                            
                            <tbody>
                                    @for (int i = 0; i < Model.Datatable.Rows.Count; i++)
                                    {
                                        <tr>
                                            @if (@Model.profession.ToLower() == "department")
                                            {
                                                <td>@Model.Datatable.Rows[i][0]</td>
                                                <td>@Model.Datatable.Rows[i][2]</td>
                                                <td>@Model.Datatable.Rows[i][1]</td>
                                            }
                                            else
                                            {
                                                @for (int j = 0; j < Model.professions[Model.profession].Item2; j++)
                                                {
                                                    <td>@Model.Datatable.Rows[i][j]</td>
                                                }
                                            }

                                            @{
                                                List<object> idJSON = new List<object>();
                                                if (Model.profession.ToLower() == "department")
                                                {

                                                    idJSON.Add(Convert.ToInt32(Model.Datatable.Rows[i][1]));
                                                }
                                                else if (Model.profession.ToLower() == "nurse_serve_at" || Model.profession.ToLower() == "doctor_work_at")
                                                {
                                                    idJSON.Add((string)Model.Datatable.Rows[i][1]);
                                                    idJSON.Add((string)Model.Datatable.Rows[i][2]);
                                                }
                                                else
                                                {
                                                    idJSON.Add((string)Model.Datatable.Rows[i][2]);
                                                }

                                            }
                                            

                                            <form method="post">
                                            <td>
                                                <input type="hidden" name="selectedItem" id="selectedItem" value="@JsonConvert.SerializeObject(idJSON)"  />
                                                <input type="hidden" name="profession" id="selectedItem" value=@Model.profession />
                                                <button class="btn btn-primary" asp-page-handler="Edit">Edit</button>
                                            </td>
                                            <td>
                                                <button class="btn btn-danger" onclick="deleteRow(this)">Delete</button>
                                            </td>
                                        </form>
                                    </tr>
                                    }
                            </tbody>
                    
                    </table>
                        </div>
                </div>
            </div>
        </div>
</div>
  </section>


</div>

<script type="text/javascript">
 $('#search-input').keyup(function () {
        var searchText = $(this).val().toLowerCase();
        $('table tbody tr').each(function () {
            var currentRow = $(this);
            var currentStaffID = currentRow.find('td:eq(2)').text().toLowerCase();
            if (currentStaffID.indexOf(searchText) !== -1) {
                currentRow.show();
            } else {
                currentRow.hide();
            }
        });
    });
</script>