HospitalManagementSystemCore/Pages/DOCTOR/DOCTOR2Dash.cshtml.cs
using HospitalManagementSystem.Models;
using HospitalManagementSystem.Pages.Manager_Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace HospitalManagementSystem.Pages.DOCTOR
{
    public class DOCTOR2DashModel : PageModel
    {
        private readonly HosDB HDB;
        private readonly ILogger<DOCTOR2DashModel> _logger;
        public DOCTOR2DashModel(ILogger<DOCTOR2DashModel> logger, HosDB HosDB)
        {
            _logger = logger;
            this.HDB = HosDB;
        }
        public string msg { get; set; }
        [BindProperty(SupportsGet = true)]
        [ViewData]
        public string sid { get; set; }

        public string mname { get; set; }

        public int nuPatients { get; set; }

        public int nuFeedback { get; set; }

        public int avgRate { get; set; }

        public DataTable appts { get; set; }

        public DataTable visits { get; set; }

        public DataTable annc { get; set; }

        public void OnGet()
        {
            sid = HttpContext.Session.GetString("sid");
            mname = HDB.getStaffFnameByID(sid);
            nuPatients = HDB.getPatientsTreatedById(sid);
            nuFeedback = HDB.getFeedbackCount(sid);
            avgRate = HDB.getAverageRating(sid);
            appts = HDB.getApptsDoc(sid);
            visits = HDB.getVisitsDoc(sid);
            annc = HDB.getAnnc();
        }
    }
}

HospitalManagementSystemCore/Pages/DOCTOR/DOCTORDash.cshtml.cs
using HospitalManagementSystem.Models;
using HospitalManagementSystem.Pages.Labtech;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Xml.Linq;

namespace HospitalManagementSystem.Pages.Manager_Pages
{
    public class ManagerDashboardModel : PageModel
    {
        private readonly HosDB HDB;
        private readonly ILogger<ManagerDashboardModel> _logger;
        public ManagerDashboardModel(ILogger<ManagerDashboardModel> logger, HosDB HosDB)
        {
            _logger = logger;
            this.HDB = HosDB;
        }
        public string msg { get; set; }
        [BindProperty(SupportsGet = true)]
        [ViewData]
        public string sid { get; set; }

        public string mname { get; set; }

        public int nuPatients { get; set; }

        public int nuFeedback { get; set; }

        public int avgRate { get; set; }

        public DataTable appts { get; set; }

        public DataTable visits { get; set; }

        public DataTable deptFeedback { get; set; }

        public DataTable annc { get; set; }

        public string deptName { get; set; }
        public void OnGet()
        {
            sid = HttpContext.Session.GetString("sid");
            mname = HDB.getStaffFnameByID(sid);
            nuPatients = HDB.getPatientsTreatedById(sid);
            nuFeedback = HDB.getFeedbackCount(sid);
            avgRate = HDB.getAverageRating(sid);
            appts = HDB.getApptsDoc(sid);
            visits = HDB.getVisitsDoc(sid);
            deptFeedback = HDB.getDeptFeedback(sid);
            annc = HDB.getAnnc();
            deptName = HDB.getDeptName(sid);

        }
    }
}

HospitalManagementSystemCore/Pages/DOCTOR/DoctorAnnouncements.cshtml.cs
using HospitalManagementSystem.Models;
using HospitalManagementSystem.Pages.Manager_Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace HospitalManagementSystem.Pages.DOCTOR
{
    public class DoctorAnnouncementsModel : PageModel
    {
        private readonly HosDB HDB;
        private readonly ILogger<DoctorAnnouncementsModel> _logger;
        public DoctorAnnouncementsModel(ILogger<DoctorAnnouncementsModel> logger, HosDB HosDB)
        {
            _logger = logger;
            this.HDB = HosDB;
        }
        public string msg { get; set; }
        [BindProperty(SupportsGet = true)]
        [ViewData]
        public string sid { get; set; }

        public string mname { get; set; }

        public DataTable annc { get; set; }
        public void OnGet()
        {
            sid = HttpContext.Session.GetString("sid");
            mname = HDB.getStaffFnameByID(sid);
            annc = HDB.getAnnc();

        }
    }
}

HospitalManagementSystemCore/Pages/DOCTOR/DoctorAppointmentRequests.cshtml.cs
using HospitalManagementSystem.Models;
using HospitalManagementSystem.Pages.Manager_Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace HospitalManagementSystem.Pages.DOCTOR
{
    public class DoctorAppointmentRequestsModel : PageModel
    {
        private readonly HosDB HDB;
        private readonly ILogger<DoctorAppointmentRequestsModel> _logger;
        public DoctorAppointmentRequestsModel(ILogger<DoctorAppointmentRequestsModel> logger, HosDB HosDB)
        {
            _logger = logger;
            this.HDB = HosDB;
        }
        public string msg { get; set; }
        [BindProperty(SupportsGet = true)]
        [ViewData]
        public string sid { get; set; }

        public string mname { get; set; }


        public DataTable appts { get; set; }

        public DataTable apptsToday { get; set; }
        public string apptIDToAdd { get; set; }
        public string diagnosis { get; set; }
        public bool isTest { get; set; }
        public string testName { get; set; }
        public IActionResult OnPostMarkAppointmenr()
        {
            //if (bool.TryParse(HttpContext.Request.Form["testNeeded"], out bool testNeededValue))
            //{
            //    isTest = testNeededValue;
            //}
            diagnosis = HttpContext.Request.Form["diagnosis"];
            apptIDToAdd = HttpContext.Request.Form["apptid"];
            testName = HttpContext.Request.Form["testname"];
            isTest = HttpContext.Request.Form["testNeeded"].ToString() == "on";

            // Use the isTest variable as needed in further logic
            // Use the isTest variable as needed in further logic

            if (isTest)
            {

                string newV = HDB.addVisit(apptIDToAdd, diagnosis);
                HDB.addTest(newV, testName);

            }
            else
            {
                string newV = HDB.addVisit(apptIDToAdd, diagnosis);

            }

            return RedirectToPage("/DOCTOR/ManagerAppointmentRequests");
        }
        public void OnGet()
        {
            string today = DateTime.Today.ToString("yyyy-MM-dd");
            sid = HttpContext.Session.GetString("sid");
            mname = HDB.getStaffFnameByID(sid);
            appts = HDB.getApptsDoc(sid);
            apptsToday = HDB.getApptsToday(sid, today);

        }
    }
}

HospitalManagementSystemCore/Pages/DOCTOR/DoctorML.cshtml.cs
using HospitalManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Security.Cryptography;
using System.Xml.Linq;

namespace HospitalManagementSystem.Pages.DOCTOR
{
    public class DoctorMLModel : PageModel
    {
        private readonly ILogger<DoctorMLModel> _logger;
        private readonly HosDB db;
        public DoctorMLModel(ILogger<DoctorMLModel> logger, HosDB db)
        {
            _logger = logger;
            this.db = db;

        }

        public DataTable MedicineTable { get; set; }
        public string ID { get; set; }
        public string sid { get; set; }

        public string mname { get; set; }
        public void OnGet()
        {
            MedicineTable = db.GetTableAdmin("Medicine");
            sid = HttpContext.Session.GetString("sid");
            mname = db.getStaffFnameByID(sid);
        }
    }
}

HospitalManagementSystemCore/Pages/DOCTOR/DoctorVisits.cshtml.cs
using ChartExample.Models.Chart;
using HospitalManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Data;
using Microsoft.AspNetCore.Http;

namespace HospitalManagementSystem.Pages.DOCTOR
{
    public class DoctorVisitsModel : PageModel
    {
        private readonly HosDB HDB;
        private readonly ILogger<DoctorVisitsModel> _logger;
        public DoctorVisitsModel(ILogger<DoctorVisitsModel> logger, HosDB HosDB)
        {
            _logger = logger;
            this.HDB = HosDB;
        }
        [BindProperty(SupportsGet = true)]
        [ViewData]
        public string sid { get; set; }

        public string mname { get; set; }

        public DataTable visits { get; set; }
        public Tuple<string[], int[]> Statistics_Of_Vistis { get; set; }
        public ChartJs Chart { get; set; }
        public string ChartJson { get; set; }


        public void OnGet()
        {
            sid = HttpContext.Session.GetString("sid");
            mname = HDB.getStaffFnameByID(sid);
            visits = HDB.getVisitsDoc(sid);
            Statistics_Of_Vistis = HDB.ViewVisitsDoctor(sid);
            var chartData = @"
                {
                type: 'bar',
                responsive: true,
                data:
                {
                labels: [] ,
                datasets: [{
                label: '',
                data: [12, 19, 3, 5, 2, 3],
                backgroundColor: [
                'rgba(255, 99, 132, 0.9)',
                'rgba(54, 162, 235, 0.9)',
                'rgba(255, 206, 86, 0.9)',
                'rgba(75, 192, 192, 0.9)',
                'rgba(153, 102, 255, 0.9)',
                'rgba(255, 159, 64, 0.9)'
                ],
                borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
                ],
              borderWidth: 1
                            }]
                },
                options: {
                    scales: {
                        x: {
                            title: {
                                display: true,
                                align: 'center',
                                text:  'Months',

                            }
                        },
                        y: {
                            title: {
                                display: true,
                                text: 'Number of visits',
                                align: 'center',
                                color: '#911',

                            },
                            ticks: {
                                beginAtZero: true,
                                    
                                }
                        }
                    }
                }
            }"; //end of chartdata

            try
            {
                Chart = JsonConvert.DeserializeObject<ChartJs>(chartData);
                string[] labelsArray = Statistics_Of_Vistis.Item1;
                Chart.data.labels = labelsArray;
                Chart.data.datasets[0].label = "Your visits";
                int[] dataArray = Statistics_Of_Vistis.Item2;
                Chart.data.datasets[0].data = dataArray;
          

                ChartJson = JsonConvert.SerializeObject(Chart, new JsonSerializerSettings
                {
                    NullValueHandling = NullValueHandling.Ignore,
                });
            }
            catch
            (Exception ex)
            { }

        }
    }
}

HospitalManagementSystemCore/Pages/DOCTOR/ManagerAnnouncements.cshtml.cs
using HospitalManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace HospitalManagementSystem.Pages.Manager_Pages
{
    public class ManagerAnnouncementsModel : PageModel
    {
        private readonly HosDB HDB;
        private readonly ILogger<ManagerAnnouncementsModel> _logger;
        public ManagerAnnouncementsModel(ILogger<ManagerAnnouncementsModel> logger, HosDB HosDB)
        {
            _logger = logger;
            this.HDB = HosDB;
        }
        public string msg { get; set; }
        [BindProperty(SupportsGet = true)]
        [ViewData]
        public string sid { get; set; }

        public string mname { get; set; }

        public DataTable annc { get; set; }

        public string newAnnc { get; set; }
        public string deptName { get; set; }
        public void OnGet()
        {
            sid = HttpContext.Session.GetString("sid");
            mname = HDB.getStaffFnameByID(sid);
            annc = HDB.getAnnc();
            deptName = HDB.getDeptName(sid);

        }
        public IActionResult OnPostAddAnnc()
        {
            sid = HttpContext.Session.GetString("sid");
            newAnnc = HttpContext.Request.Form["content"];
            string date = DateTime.Now.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss");
            HDB.AddAnnc(sid, date, newAnnc);
            return RedirectToPage("/DOCTOR/ManagerAnnouncements");

        }
    }
}

HospitalManagementSystemCore/Pages/DOCTOR/ManagerAppointmentRequests.cshtml.cs
using HospitalManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis;
using System.Data;

namespace HospitalManagementSystem.Pages.Manager_Pages
{
    public class ManagerAppointmentRequestsModel : PageModel
    {
        private readonly HosDB HDB;
        private readonly ILogger<ManagerAppointmentRequestsModel> _logger;
        public ManagerAppointmentRequestsModel(ILogger<ManagerAppointmentRequestsModel> logger, HosDB HosDB)
        {
            _logger = logger;
            this.HDB = HosDB;
        }
        public string msg { get; set; }
        [BindProperty(SupportsGet = true)]
        [ViewData]
        public string sid { get; set; }

        public string mname { get; set; }


        public DataTable appts { get; set; }

        public DataTable apptsToday { get; set; }
        public string deptName { get; set; }

        public string apptIDToAdd { get; set; } 
        public string diagnosis { get; set; }
        public bool isTest { get; set; }

        public string testName { get; set; }
        public IActionResult OnPostMarkAppointmenr()
        {
            //if (bool.TryParse(HttpContext.Request.Form["testNeeded"], out bool testNeededValue))
            //{
            //    isTest = testNeededValue;
            //}
            diagnosis = HttpContext.Request.Form["diagnosis"];
            apptIDToAdd = HttpContext.Request.Form["apptid"];
            testName = HttpContext.Request.Form["testname"];
             isTest = HttpContext.Request.Form["testNeeded"].ToString() == "on";

            // Use the isTest variable as needed in further logic
            // Use the isTest variable as needed in further logic

            if (isTest)
            {

                string newV = HDB.addVisit(apptIDToAdd, diagnosis);
                HDB.addTest(newV, testName);

            }
            else
            {
                string newV = HDB.addVisit(apptIDToAdd, diagnosis);

            }

            return RedirectToPage("/DOCTOR/ManagerAppointmentRequests");
        }
        public void OnGet()
        {
            string today = DateTime.Today.ToString("yyyy-MM-dd");
            sid = HttpContext.Session.GetString("sid");
            mname = HDB.getStaffFnameByID(sid);
            appts = HDB.getApptsDoc(sid);
            deptName = HDB.getDeptName(sid);
            apptsToday = HDB.getApptsToday(sid, today);

        }
    }
}

HospitalManagementSystemCore/Pages/DOCTOR/ManagerCharts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HospitalManagementSystem.Pages.Manager_Pages
{
    public class ManagerChartsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HospitalManagementSystemCore/Pages/DOCTOR/ManagerDepartement.cshtml.cs
using HospitalManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace HospitalManagementSystem.Pages.Manager_Pages
{
    public class ManagerDepartementModel : PageModel
    {
        private readonly HosDB HDB;
        private readonly ILogger<ManagerDepartementModel> _logger;
        public ManagerDepartementModel(ILogger<ManagerDepartementModel> logger, HosDB HosDB)
        {
            _logger = logger;
            this.HDB = HosDB;
        }

        [BindProperty(SupportsGet = true)]
        [ViewData]
        public string sid { get; set; }
        public string mname { get; set; }
        public int deptAvgRate { get; set; }
        public DataTable deptFeedback { get; set; }
        public string deptName { get; set; }

        public int nuFeedbackDept { get; set; }
        public void OnGet()
        {
            sid = HttpContext.Session.GetString("sid");
            mname = HDB.getStaffFnameByID(sid);
            deptFeedback = HDB.getDeptFeedback(sid);
            deptName = HDB.getDeptName(sid);
            deptAvgRate = HDB.getDeptAvgRate(sid);
            nuFeedbackDept = HDB.getNuFeebackDept(sid);

        }
    }
}

HospitalManagementSystemCore/Pages/Navbar_Pages/Doctors.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HospitalManagementSystem.Pages.Navnar_Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HospitalManagementSystemCore/Pages/DOCTOR/DoctorAnnouncements.cshtml
@page
@model HospitalManagementSystem.Pages.DOCTOR.DoctorAnnouncementsModel
@{
    Layout = "_LayoutDoctor2";
}

<div class="content-wrap">
    <div class="main">
        <div class="container-fluid">
            <div class="page-title">
                <h3 style="padding:5px">Hello, @Model.mname. <span>Welcome Here</span></h3>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-title">
                            <h4>Announcements</h4>
                        </div>
                        <div class="card-body">
                            <div class="card shadow" style="border-radius: 1rem 1rem 1rem 1rem;">
                                <div class="card-body">
                                    @for (int i = 0; i < Model.annc.Rows.Count; i++)
                                    {
                                        <div class="card">
                                            <div class="card-title">
                                                @Model.annc.Rows[i][0]
                                            </div>
                                            <div class="card-body">
                                                <div class="ct-bar-chart m-t-30">
                                                    <p>@Model.annc.Rows[i][2]</p>
                                                </div>
                                            </div>
                                            <div class="float-xl-end">@Model.annc.Rows[i][1]</div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HospitalManagementSystemCore/Pages/DOCTOR/DoctorAppointmentRequests.cshtml
@page
@model HospitalManagementSystem.Pages.DOCTOR.DoctorAppointmentRequestsModel
@{
    Layout = "_LayoutDoctor2";
}
<div class="content-wrap">
    <div class="main">
        <div class="container-fluid">
            <div class="page-title">
                <h3 style="padding:5px">Hello, @Model.mname. <span>Welcome Here</span></h3>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-title">
                            <h4>Today Appointment Requests</h4>
                        </div>
                        <div class="card-body">
                            <div class="card shadow" style="border-radius: 1rem 1rem 1rem 1rem;">
                                <div class="card-body">
                                    <table class="table table-responsive-xl table-hover">
                                        <thead>
                                            <tr>
                                                <th>Patient Name</th>
                                                <th>Type</th>
                                                <th>Appointment Date</th>
                                                <th>Appointment Time</th>
                                                <th>Notes</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @for (int i = 0; i < Model.apptsToday.Rows.Count; i++)
                                            {
                                                <tr>
                                                    <th scope="row">@Model.apptsToday.Rows[i][0]</th>
                                                    @for (int j = 1; j < Model.apptsToday.Columns.Count - 1; j++)
                                                    {
                                                        if (j == 1)
                                                        {
                                                            <td><a href="/Patient_Pages/RecordForMS?pid=@ViewData["@Model.apptsToday.Rows[6]"]&sid=@ViewData["sid"]">@Model.apptsToday.Rows[i][j]</a></td>
                                                        }
                                                        else
                                                        {
                                                            <td>@Model.apptsToday.Rows[i][j]</td>

                                                        }
                                                    }
                                                </tr>
                                                <form method="post" asp-page-handler="MarkAppointmenr">
                                                    <input type="hidden" name="apptid" id="selectedItem" value="@Model.apptsToday.Rows[i][5]" />
                                            <td>
                                                <input type="text" id="diagnosisInput" placeholder="Enter Diagnosis" name="diagnosis" required>
                                            </td>
                                            <td>
                                                <label for="testCheckbox">Test needed:</label>
                                                <input type="checkbox" id="testCheckbox" name="testNeeded" onclick="toggleTestNameInput()" checked="@(0 == 1)">
                                            </td>
                                            <td>
                                                <input type="text" id="testNameInput" placeholder="Enter Test(s) Required" name="testName" class="hidden">
                                            </td>
                                            <td>
                                                <input type="submit" value="Submit">
                                            </td>
                                            </form>
                                            }

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-title">
                            <h4>Appointment Requests</h4>
                        </div>
                        <div class="card-body">
                            <div class="card shadow" style="border-radius: 1rem 1rem 1rem 1rem;">
                                <div class="card-body">

                                    <table class="table table-responsive-xl table-hover">
                                        <thead>
                                            <tr>
                                                <th>Patient Name</th>
                                                <th>Type</th>
                                                <th>Appointment Date</th>
                                                <th>Appointment Time</th>
                                                <th>Notes</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @for (int i = 0; i < Model.appts.Rows.Count; i++)
                                            {
                                                <tr>
                                                    <th scope="row">@Model.appts.Rows[i][0]</th>
                                                    @for (int j = 1; j < Model.appts.Columns.Count; j++)
                                                    {
                                                        if (j == 2)
                                                        {
                                                            <td>@(((DateTime)Model.appts.Rows[i][j]).ToShortDateString())</td>
                                                        }
                                                        else
                                                        {
                                                            <td>@Model.appts.Rows[i][j]</td>

                                                        }
                                                    }
                                                </tr>
                                            }

                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function toggleTestNameInput() {
        var testNameInput = document.getElementById('testNameInput');
        testNameInput.classList.toggle('hidden');
    }
</script>

HospitalManagementSystemCore/Pages/DOCTOR/DoctorML.cshtml
@page
@model HospitalManagementSystem.Pages.DOCTOR.DoctorMLModel
@{
    Layout = "_LayoutDoctor2";
}

<div class="content-wrap">
    <div class="main">

        <div class="container-fluid">
            <div class="page-title">
                <h3 style="padding:5px">Hello, @Model.mname. <span>Welcome Here</span></h3>
            </div>
            <section>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card" style="border-radius: 1rem 1rem 1rem 1rem;">
                            <h2 class="h3 m-4 grey-text" style="font-family: 'Poppins';">Medicine List</h2>
                            <div class="card-body">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>Medicine Name</th>
                                            <th>Amount Available</th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @for (int i = 0; i < Model.MedicineTable.Rows.Count; i++)
                                        {

                                            <tr>
                                                <td>@Model.MedicineTable.Rows[i][0]</td>
                                                <td><span class="amount">@Model.MedicineTable.Rows[i][1]</span></td>
                                                <form method="post">
                                                    <input type="hidden" name="id" id="id" value="@Model.ID">
                                                    <input type="hidden" name="name" id="name" value="@Model.MedicineTable.Rows[i][0]">
                                                </form>
                                            </tr>

                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

HospitalManagementSystemCore/Pages/DOCTOR/ManagerAnnouncements.cshtml
@page
@model HospitalManagementSystem.Pages.Manager_Pages.ManagerAnnouncementsModel
@{
	Layout = "_LayoutDoctor";
}

<div class="content-wrap">
    <div class="main">
        <div class="container-fluid">
            <div class="page-title">
                <h3 style="padding:5px">Hello, @Model.mname. <span>Welcome Here</span></h3>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-title">
                            <h4>Add Announcement</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <form asp-page-handler="AddAnnc">
                                    <input type="text" name="content" id="selectedItem" required />
                                    <input type="submit" value="Submit" required>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-title">
                            <h4>Announcements</h4>
                        </div>
                        <div class="card-body">
                            <div class="card shadow" style="border-radius: 1rem 1rem 1rem 1rem;">
                                <div class="card-body">
                                    @for (int i = 0; i < Model.annc.Rows.Count; i++)
                                    {
                                        <div class="card">
                                            <div class="card-title">
                                                @Model.annc.Rows[i][0]
                                            </div>
                                            <div class="card-body">
                                                <div class="ct-bar-chart m-t-30">
                                                    <p>@Model.annc.Rows[i][2]</p>
                                                </div>
                                            </div>
                                            <div class="float-xl-end">@Model.annc.Rows[i][1]</div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>